In [1]:
import pandas as pd

In [2]:
ratings = pd.read_csv('../data/raw/ml-100k/u.data',sep='\t',names = ['user_id','movie_id','rating','timestamp'])
print(ratings.head(5))

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [3]:
movies = pd.read_csv('../data/raw/ml-100k/u.item',sep='|',encoding='latin-1',names = ['movie_id','movie_title'] + list(range(22)))
print(movies.head(5))

   movie_id        movie_title            0   1  \
0         1   Toy Story (1995)  01-Jan-1995 NaN
1         2   GoldenEye (1995)  01-Jan-1995 NaN
2         3  Four Rooms (1995)  01-Jan-1995 NaN
3         4  Get Shorty (1995)  01-Jan-1995 NaN
4         5     Copycat (1995)  01-Jan-1995 NaN

                                                   2  3  4  5  6  7  ...  12  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...  0  0  0  1  1  ...   0
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...  0  1  1  0  0  ...   0
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...  0  0  0  0  0  ...   0
3  http://us.imdb.com/M/title-exact?Get%20Shorty%...  0  1  0  0  0  ...   0
4  http://us.imdb.com/M/title-exact?Copycat%20(1995)  0  0  0  0  0  ...   0

   13  14  15  16  17  18  19  20  21
0   0   0   0   0   0   0   0   0   0
1   0   0   0   0   0   0   1   0   0
2   0   0   0   0   0   0   1   0   0
3   0   0   0   0   0   0   0   0   0
4   0   0   0   0   0   0   1   0   0

[5 rows x 24 columns]

In [4]:
movies = movies[['movie_id','movie_title']]
print(movies.head(5))

   movie_id        movie_title
0         1   Toy Story (1995)
1         2   GoldenEye (1995)
2         3  Four Rooms (1995)
3         4  Get Shorty (1995)
4         5     Copycat (1995)

In [5]:
data = pd.read_csv('../data/raw/data.csv')
data.head(50)

,user_id,movie_id,rating,movie_title
0,196,242,3,Kolya (1996)
1,186,302,3,L.A. Confidential (1997)
2,22,377,1,Heavyweights (1994)
3,244,51,2,Legends of the Fall (1994)
4,166,346,1,Jackie Brown (1997)
5,298,474,4,Dr. Strangelove or: How I Learned to Stop Worr...
6,115,265,2,"Hunt for Red October, The (1990)"
7,253,465,5,"Jungle Book, The (1994)"
8,305,451,3,Grease (1978)
9,6,86,3,"Remains of the Day, The (1993)"
10,62,257,2,Men in Black (1997)
11,286,1014,5,Romy and Michele's High School Reunion (1997)
12,200,222,5,Star Trek: First Contact (1996)
13,210,40,3,"To Wong Foo, Thanks for Everything! Julie Newm..."
14,224,29,3,Batman Forever (1995)
15,303,785,3,Only You (1994)
16,122,387,5,"Age of Innocence, The (1993)"
17,194,274,2,Sabrina (1995)
18,291,1042,4,Just Cause (1995)
19,234,1184,2,"Endless Summer 2, The (1994)"
20,119,392,4,"Man Without a Face, The (1993)"
21,167,486,4,Sabrina (1954)
22,299,144,4,Die Hard (1988)
23,291,118,2,Twister (1996)
24,308,1,4,Toy Story (1995)
25,95,546,2,Broken Arrow (1996)
26,38,95,5,Aladdin (1992)
27,102,768,2,Casper (1995)
28,63,277,4,Restoration (1995)
29,160,234,5,Jaws (1975)
30,50,246,3,Chasing Amy (1997)
31,301,98,4,"Silence of the Lambs, The (1991)"
32,225,193,4,"Right Stuff, The (1983)"
33,290,88,4,Sleepless in Seattle (1993)
34,97,194,3,"Sting, The (1973)"
35,157,274,4,Sabrina (1995)
36,181,1081,1,Curdled (1996)
37,278,603,5,Rear Window (1954)
38,276,796,1,Speechless (1994)
39,7,32,4,Crumb (1994)
40,10,16,4,French Twist (Gazon maudit) (1995)
41,284,304,4,Fly Away Home (1996)
42,201,979,2,"Trigger Effect, The (1996)"
43,276,564,3,Tales from the Hood (1995)
44,287,327,5,Cop Land (1997)
45,246,201,5,Evil Dead II (1987)
46,242,1137,5,Beautiful Thing (1996)
47,249,241,5,"Last of the Mohicans, The (1992)"
48,99,4,5,Get Shorty (1995)
49,178,332,3,Kiss the Girls (1997)

In [6]:
data.describe(include='all')

             user_id       movie_id         rating       movie_title
count   100000.00000  100000.000000  100000.000000            100000
unique           NaN            NaN            NaN              1664
top              NaN            NaN            NaN  Star Wars (1977)
freq             NaN            NaN            NaN               583
mean       462.48475     425.530130       3.529860               NaN
std        266.61442     330.798356       1.125674               NaN
min          1.00000       1.000000       1.000000               NaN
25%        254.00000     175.000000       3.000000               NaN
50%        447.00000     322.000000       4.000000               NaN
75%        682.00000     631.000000       4.000000               NaN
max        943.00000    1682.000000       5.000000               NaN

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   user_id      100000 non-null  int64
 1   movie_id     100000 non-null  int64
 2   rating       100000 non-null  int64
 3   movie_title  100000 non-null  object
dtypes: int64(3), object(1)
memory usage: 3.1+ MB

In [8]:
data.head(5)

   user_id  movie_id  rating                 movie_title
0      196       242       3                Kolya (1996)
1      186       302       3    L.A. Confidential (1997)
2       22       377       1         Heavyweights (1994)
3      244        51       2  Legends of the Fall (1994)
4      166       346       1         Jackie Brown (1997)

In [10]:

data.duplicated().sum()

0

In [19]:
user_counts = data['user_id'].value_counts()
print(user_counts.head())
print(user_counts.describe())

user_id
405    737
655    685
13     636
450    540
276    518
Name: count, dtype: int64
count    943.000000
mean     106.044539
std      100.931743
min       20.000000
25%       33.000000
50%       65.000000
75%      148.000000
max      737.000000
Name: count, dtype: float64

In [25]:
active_users = user_counts[user_counts > 20].index
data = data[data['user_id'].isin(active_users)]
data.shape

(99360, 4)

In [26]:
movie_counts = data['movie_id'].value_counts()
print(movie_counts.head())

movie_id
50     580
181    504
100    500
258    495
294    468
Name: count, dtype: int64

In [30]:
active_movies = movie_counts[movie_counts > 20].index
data = data[data['movie_id'].isin(active_movies)]
data.shape

(94113, 4)